name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^12.0.1
  flutter_adaptive_scaffold: ^0.1.7+1
  uuid: ^4.1.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  shimmer_animation: ^2.1.0+1
  json_annotation: ^4.8.1
  hive: ^2.2.3
  flex_color_picker: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.3

  flutter_lints: ^3.0.0
  mocktail: ^1.0.1
  bloc_test: ^9.1.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true